### ISSUE TITLE
如何支持beta 8.1版本

### ISSUE THREAD

**Issue by weichen-ink** [cosname/flarum-chinese-search#1]
你好，找了很久的中文搜索插件，看到这个
但是flarum已经是8.1版本了，请问如何才能升级支持呢，万分感谢

**Comment by yixuan** [comment]
这个支持 8.1，但功能非常不完善，可能不是你想要的，参见讨论：<https://d.cosx.org/d/420412/9>。

**Comment by weichen-ink** [comment]
composer提示这个错误，小白了。。。求教
[InvalidArgumentException]
                                              
  Could not find a version of package cosname/flarum-chinese-search matching your minimum-stability (beta). Require it with an explicit version constraint allowing its desired stability.

**Comment by yixuan** [comment]
再次警告，这个插件会非常占用服务器资源，而且功能也不完善。如果确定要试一试，在 `composer.json` 里面加上

```
    "require": {
        "cosname/flarum-chinese-search": "dev-master"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cosname/flarum-chinese-search.git"
        }
    ]
```

然后 `composer update` 进行更新。
